# Generated by Django 4.2.7 on 2024-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orgao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica se o usuário pode acessar este site de administração.', verbose_name='status de staff'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indica que este usuário possui todas as permissões sem atribuí-las explicitamente.', verbose_name='status de superusuário'),
        ),
    ]
