# Generated by Django 4.2.7 on 2024-09-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_orgao_alter_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_confirmation',
        ),
    ]
